apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.alpha.kubernetes.io/storage-class: anything
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: null
  labels:
    app: vitess
    cell: zone1
    component: vttablet
    keyspace: main
    shard: 80-x
    type: replica
  name: vtdataroot-zone1-main-80-x-replica-0
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/vtdataroot-zone1-main-80-x-replica-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: pvc-fc99927d-e6c6-11e7-a564-42010a920fd3
status: {}
