apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vitess
    cell: global
    component: etcd
  name: etcd-global-srv
  selfLink: /api/v1/namespaces/default/services/etcd-global-srv
spec:
  clusterIP: None
  ports:
  - name: etcd-server
    port: 7001
    protocol: TCP
    targetPort: 7001
  selector:
    app: vitess
    cell: global
    component: etcd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
