apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vitess
    cell: global
    component: etcd
  name: etcd-global
  selfLink: /api/v1/namespaces/default/services/etcd-global
spec:
  clusterIP: <unknown>
  ports:
  - port: 4001
    protocol: TCP
    targetPort: 4001
  selector:
    app: vitess
    cell: global
    component: etcd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
