apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vitess
    component: orchestrator
  name: orchestrator
  selfLink: /api/v1/namespaces/default/services/orchestrator
spec:
  clusterIP: <unknown>
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: vitess
    component: orchestrator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
