apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vitess
    component: vtctld
  name: vtctld
  selfLink: /api/v1/namespaces/default/services/vtctld
spec:
  clusterIP: <unknown>
  ports:
  - name: web
    port: 15000
    protocol: TCP
    targetPort: 15000
  - name: grpc
    port: 15999
    protocol: TCP
    targetPort: 15999
  selector:
    app: vitess
    component: vtctld
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
