apiVersion: v1
kind: Service
metadata:
  name: vttablet
  labels:
    app: vitess
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 15002
      name: web
    - port: 16002
      name: grpc
  clusterIP: None
  selector:
    app: vitess
    component: vttablet
