CREATE TABLE tbl_metering_group_data_5_min (
  created_ts bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'milisecond unit',
  created_date datetime NOT NULL,
  serial_id char(12) COLLATE utf8_unicode_ci NOT NULL DEFAULT '000000000000' COMMENT 'came from MAC Addres',
  group_id tinyint(5) unsigned NOT NULL DEFAULT '0',

  phase_voltage_min float DEFAULT NULL,
  phase_voltage_max float DEFAULT NULL,
  phase_voltage_avg float DEFAULT NULL,
  phase_voltage_first float DEFAULT NULL,
  phase_voltage_last float DEFAULT NULL,

  line_voltage_min float DEFAULT NULL,
  line_voltage_max float DEFAULT NULL,
  line_voltage_avg float DEFAULT NULL,
  line_voltage_first float DEFAULT NULL,
  line_voltage_last float DEFAULT NULL,

  voltage_crest_factor_min float DEFAULT NULL,
  voltage_crest_factor_max float DEFAULT NULL,
  voltage_crest_factor_avg float DEFAULT NULL,
  voltage_crest_factor_first float DEFAULT NULL,
  voltage_crest_factor_last float DEFAULT NULL,

  phase_current_min float DEFAULT NULL,
  phase_current_max float DEFAULT NULL,
  phase_current_avg float DEFAULT NULL,
  phase_current_first float DEFAULT NULL,
  phase_current_last float DEFAULT NULL,

  current_crest_factor_min float DEFAULT NULL,
  current_crest_factor_max float DEFAULT NULL,
  current_crest_factor_avg float DEFAULT NULL,
  current_crest_factor_first float DEFAULT NULL,
  current_crest_factor_last float DEFAULT NULL,

  active_power_min float DEFAULT NULL,
  active_power_max float DEFAULT NULL,
  active_power_avg float DEFAULT NULL,
  active_power_first float DEFAULT NULL,
  active_power_last float DEFAULT NULL,

  reactive_power_min float DEFAULT NULL,
  reactive_power_max float DEFAULT NULL,
  reactive_power_avg float DEFAULT NULL,
  reactive_power_first float DEFAULT NULL,
  reactive_power_last float DEFAULT NULL,

  power_factor_min float DEFAULT NULL,
  power_factor_max float DEFAULT NULL,
  power_factor_avg float DEFAULT NULL,
  power_factor_first float DEFAULT NULL,
  power_factor_last float DEFAULT NULL,

  frequency_min float DEFAULT NULL,                    
  frequency_max float DEFAULT NULL,     
  frequency_avg float DEFAULT NULL,     
  frequency_first float DEFAULT NULL,     
  frequency_last float DEFAULT NULL,     

  thd_phase_voltage_min float DEFAULT NULL,
  thd_phase_voltage_max float DEFAULT NULL,
  thd_phase_voltage_avg float DEFAULT NULL,
  thd_phase_voltage_first float DEFAULT NULL,
  thd_phase_voltage_last float DEFAULT NULL,

  thd_phase_current_min float DEFAULT NULL,
  thd_phase_current_max float DEFAULT NULL,
  thd_phase_current_avg float DEFAULT NULL,
  thd_phase_current_first float DEFAULT NULL,
  thd_phase_current_last float DEFAULT NULL,

  temperature_min float DEFAULT NULL,
  temperature_max float DEFAULT NULL,
  temperature_avg float DEFAULT NULL,
  temperature_first float DEFAULT NULL,
  temperature_last float DEFAULT NULL,

  voltage_harmonics_min float DEFAULT NULL,
  voltage_harmonics_max float DEFAULT NULL,
  voltage_harmonics_avg float DEFAULT NULL,
  voltage_harmonics_first float DEFAULT NULL,
  voltage_harmonics_last float DEFAULT NULL,

  current_harmonics_min float DEFAULT NULL,
  current_harmonics_max float DEFAULT NULL,
  current_harmonics_avg float DEFAULT NULL,
  current_harmonics_first float DEFAULT NULL,
  current_harmonics_last float DEFAULT NULL,

  apparent_power_min float DEFAULT NULL,
  apparent_power_max float DEFAULT NULL,
  apparent_power_avg float DEFAULT NULL,
  apparent_power_first float DEFAULT NULL,
  apparent_power_last float DEFAULT NULL,

  inverter_conversion_efficiency_min float DEFAULT NULL,
  inverter_conversion_efficiency_max float DEFAULT NULL,
  inverter_conversion_efficiency_avg float DEFAULT NULL,
  inverter_conversion_efficiency_first float DEFAULT NULL,
  inverter_conversion_efficiency_last float DEFAULT NULL,

  electric_charge_min float DEFAULT NULL,
  electric_charge_max float DEFAULT NULL,
  electric_charge_avg float DEFAULT NULL,
  electric_charge_first float DEFAULT NULL,
  electric_charge_last float DEFAULT NULL,

  line_voltage_R_S_min float DEFAULT NULL,
  line_voltage_R_S_max float DEFAULT NULL,
  line_voltage_R_S_avg float DEFAULT NULL,
  line_voltage_R_S_first float DEFAULT NULL,
  line_voltage_R_S_last float DEFAULT NULL,

  line_voltage_S_T_min float DEFAULT NULL,
  line_voltage_S_T_max float DEFAULT NULL,
  line_voltage_S_T_avg float DEFAULT NULL,
  line_voltage_S_T_first float DEFAULT NULL,
  line_voltage_S_T_last float DEFAULT NULL,

  line_voltage_T_R_min float DEFAULT NULL,
  line_voltage_T_R_max float DEFAULT NULL,
  line_voltage_T_R_avg float DEFAULT NULL,
  line_voltage_T_R_first float DEFAULT NULL,
  line_voltage_T_R_last float DEFAULT NULL,

  accumulate_power_consumption_min float DEFAULT NULL,
  accumulate_power_consumption_max float DEFAULT NULL,
  accumulate_power_consumption_avg float DEFAULT NULL,
  accumulate_power_consumption_first float DEFAULT NULL,
  accumulate_power_consumption_last float DEFAULT NULL,

  dc_voltage_min float DEFAULT NULL,
  dc_voltage_max float DEFAULT NULL,
  dc_voltage_avg float DEFAULT NULL,
  dc_voltage_first float DEFAULT NULL,
  dc_voltage_last float DEFAULT NULL,

  dc_current_min float DEFAULT NULL,
  dc_current_max float DEFAULT NULL,
  dc_current_avg float DEFAULT NULL,
  dc_current_first float DEFAULT NULL,
  dc_current_last float DEFAULT NULL,

  dc_electric_power_min float DEFAULT NULL,
  dc_electric_power_max float DEFAULT NULL,
  dc_electric_power_avg float DEFAULT NULL,
  dc_electric_power_first float DEFAULT NULL,
  dc_electric_power_last float DEFAULT NULL,

  dc_ampere_min float DEFAULT NULL,
  dc_ampere_max float DEFAULT NULL,
  dc_ampere_avg float DEFAULT NULL,
  dc_ampere_first float DEFAULT NULL,
  dc_ampere_last float DEFAULT NULL,

  accumulate_dc_power_consumption_min float DEFAULT NULL,
  accumulate_dc_power_consumption_max float DEFAULT NULL,
  accumulate_dc_power_consumption_avg float DEFAULT NULL,
  accumulate_dc_power_consumption_first float DEFAULT NULL,
  accumulate_dc_power_consumption_last float DEFAULT NULL,

  PRIMARY KEY (serial_id, created_ts, group_id)
) ENGINE=InnoDB
