CREATE TABLE tbl_metering_group_data (
	id bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
	created_ts bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'milisecond unit',
	created_date datetime NOT NULL,
	serial_id char(12) COLLATE utf8_unicode_ci NOT NULL DEFAULT '000000000000' COMMENT 'came from MAC Addres',
	group_id tinyint(5) unsigned NOT NULL DEFAULT '0',
	phase_voltage float DEFAULT NULL,
	line_voltage float DEFAULT NULL,
	voltage_crest_factor float DEFAULT NULL,
	phase_current float DEFAULT NULL,
	current_crest_factor float DEFAULT NULL,
	active_power float DEFAULT NULL,
	reactive_power float DEFAULT NULL,
	power_factor float DEFAULT NULL,
	frequency float DEFAULT NULL,
	thd_phase_voltage float DEFAULT NULL,
	thd_phase_current float DEFAULT NULL,
	temperature float DEFAULT NULL,
	voltage_harmonics float DEFAULT NULL,
	current_harmonics float DEFAULT NULL,
	apparent_power float DEFAULT NULL,
	inverter_conversion_efficiency float DEFAULT NULL,
	electric_charge float DEFAULT NULL,
	line_voltage_R_S float DEFAULT NULL,
	line_voltage_S_T float DEFAULT NULL,
	line_voltage_T_R float DEFAULT NULL,
	accumulate_power_consumption float DEFAULT NULL,
	dc_voltage float DEFAULT NULL,
	dc_current float DEFAULT NULL,
	dc_electric_power float DEFAULT NULL,
	dc_ampere float DEFAULT NULL,
	accumulate_dc_power_consumption float DEFAULT NULL,
	INDEX (created_ts, serial_id, group_id),
	INDEX (serial_id, created_ts, group_id) 
) ENGINE=InnoDB
